import { assert, assertEquals, assertNotEquals, assertStringIncludes } from "https://deno.land/std@0.224.0/assert/mod.ts";
import type { RenderInput } from "../hireOrders.ts";
import { buildStyles, renderHireOrderPdf } from "./render.tsx";
import { extractPdfText } from "./pdfText.ts";
import { resolveHireOrderCopy } from "./pdfCopy.ts";
import { resolveHireOrderTheme } from "./pdfTheme.ts";

/** Decode the single unfiltered RGBA scanline used by the tiny signature fixture. */
async function decodeSignatureFixturePixels(dataUrl: string): Promise<Uint8Array> {
  const encoded = dataUrl.slice(dataUrl.indexOf(",") + 1);
  const png = Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0));
  const idatParts: Uint8Array[] = [];
  let offset = 8; // PNG signature
  while (offset < png.length) {
    const length = new DataView(png.buffer, png.byteOffset + offset, 4).getUint32(0);
    const type = new TextDecoder().decode(png.slice(offset + 4, offset + 8));
    if (type === "IDAT") idatParts.push(png.slice(offset + 8, offset + 8 + length));
    offset += 12 + length;
  }
  const compressedBytes = new Uint8Array(
    idatParts.reduce((total, part) => total + part.length, 0),
  );
  let compressedOffset = 0;
  for (const part of idatParts) {
    compressedBytes.set(part, compressedOffset);
    compressedOffset += part.length;
  }
  const compressed = new Blob([compressedBytes.buffer]);
  const inflated = new Uint8Array(
    await new Response(
      compressed.stream().pipeThrough(new DecompressionStream("deflate")),
    ).arrayBuffer(),
  );
  assertEquals(inflated[0], 0, "fixture uses an unfiltered PNG scanline");
  return inflated.slice(1);
}

/** A full OrderData plus letterhead and terms — the shape Task 8 will pass. */
function makeRenderFixture(): RenderInput {
  return {
    data: {
      artist_name: { value: "Mara Müller", source: "showflow" },
      recipient_email: { value: "mara@example.de", source: "showflow" },
      role: { value: "Lead vocalist", source: "showflow" },
      cast: { value: "Berlin 1", source: "showflow" },
      date: { value: "2026-06-15", source: "showflow" },
      venue: { value: "Colosseum Berlin", source: "sheet" },
      city: { value: "Berlin", source: "showflow" },
      duration_min: { value: 90, source: "manual" },
      sessions: { value: ["19:00", "21:00"], source: "showflow" },
      fee: { value: "4500.00", source: "sheet" },
      currency: { value: "EUR", source: "default" },
      notes: { value: "Backline provided by the venue.", source: "manual" },
    },
    orderNo: "HO-2026-0615-B1",
    status: "issued",
    letterhead: {
      legal_name: "Nord Productions GmbH",
      address_lines: ["Chausseestrasse 12", "10115 Berlin", "Germany"],
      registration_line: "HRB 123456 B, VAT DE123456789",
      agent_name: "Jonas Wagner",
      agent_email: "jonas@nordproductions.de",
    },
    terms: [
      {
        title: "Engagement",
        body: "The Producer engages the Artist to perform at the venue on the date stated above.",
      },
      {
        title: "Cancellation",
        body: "Either party may cancel in writing no later than 14 days before the performance date.",
      },
    ],
    currency: "EUR",
    generatedAtIso: "2026-05-02T09:30:00.000Z",
  };
}

Deno.test("renders a parseable pdf with the core fields", async () => {
  const bytes = await renderHireOrderPdf(makeRenderFixture());

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  assert(bytes.length > 5_000, `expected a real document, got ${bytes.length} bytes`);

  // Assert what the document SAYS, not just that bytes exist: a PDF of the
  // right size with blank pages would pass the two checks above.
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Performance contract");
  assertStringIncludes(text, "HO-2026-0615-B1");
  assertStringIncludes(text, "Nord Productions GmbH");
  assertStringIncludes(text, "Colosseum Berlin");
  assertStringIncludes(text, "Lead vocalist");
  assertStringIncludes(text, "Berlin 1");
  assertStringIncludes(text, "15/06/2026");
  assertStringIncludes(text, "90 min");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "Generated by ShowFlow Pro");
  // Running order rows come from `sessions`.
  assertStringIncludes(text, "Session 1");
  assertStringIncludes(text, "19:00");
  assertStringIncludes(text, "Session 2");
  assertStringIncludes(text, "21:00");
  // Terms are the caller's, rendered as numbered clauses.
  assertStringIncludes(text, "Terms & conditions");
  assertStringIncludes(text, "Engagement.");
  assertStringIncludes(text, "Either party may cancel in writing");
  // Both signature lines.
  assertStringIncludes(text, "For the Producer");
  assertStringIncludes(text, "The Artist");
});

Deno.test("embeds glyphs for non-ASCII copy rather than dropping them", async () => {
  // The Task 5 spike ran ASCII-only against a Latin-subset font and flagged
  // that unmapped glyphs would silently render as notdef. These assert the
  // full fonts really carry the umlaut and the euro sign.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));
  assertStringIncludes(text, "Mara Müller");
  assertStringIncludes(text, "€4,500.00");
});

Deno.test("preview watermark only in preview status", async () => {
  const issued = await renderHireOrderPdf({ ...makeRenderFixture(), status: "issued" });
  const preview = await renderHireOrderPdf({ ...makeRenderFixture(), status: "preview" });

  // Assert the watermark by its text, not by `preview.length !== issued.length`
  // (which any styling difference would satisfy).
  assertStringIncludes(await extractPdfText(preview), "PREVIEW");
  assertEquals((await extractPdfText(issued)).includes("PREVIEW"), false);
});

Deno.test("renders without a dangling heading when the org has no terms", async () => {
  // Org terms ship empty by product decision, so this is the default document,
  // not an edge case.
  const bytes = await renderHireOrderPdf({ ...makeRenderFixture(), terms: [] });

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  const text = await extractPdfText(bytes);
  assertEquals(text.includes("Terms & conditions"), false);
  // The rest of the document still renders.
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "For the Producer");
});

Deno.test("renders only an engagement fee, never a deposit or balance", async () => {
  // v1 is fee-only: the design mock's deposit/balance rows are a non-goal.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertStringIncludes(text, "Engagement fee");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertEquals(text.includes("Deposit"), false);
  assertEquals(text.includes("Balance"), false);
});

Deno.test("renders no em-dashes or en-dashes in the document copy", async () => {
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertEquals(text.includes("—"), false, "em-dash found in rendered copy");
  assertEquals(text.includes("–"), false, "en-dash found in rendered copy");
});

Deno.test("an org copy override changes the printed heading", async () => {
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    copy: resolveHireOrderCopy({ terms_heading: "Conditions of engagement" }),
  });
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Conditions of engagement");
  assertEquals(text.includes("Terms & conditions"), false);
});

Deno.test("omitting copy renders the stock defaults unchanged", async () => {
  // No `copy` on the input -> the renderer falls back to the built-in defaults,
  // so existing callers/tests are byte-for-byte unaffected.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));
  assertStringIncludes(text, "Terms & conditions");
  assertStringIncludes(text, "Performance contract");
});

const BASE: RenderInput = {
  data: {
    artist_name: { value: "Ann Lee", source: "showflow" },
    recipient_email: { value: "ann@x.de", source: "showflow" },
    date: { value: "2026-08-15", source: "showflow" },
    venue: { value: "Tempodrom", source: "showflow" },
    fee: { value: 850, source: "showflow" },
  },
  orderNo: "HO-1",
  status: "issued",
  letterhead: { legal_name: "Nord GmbH", address_lines: ["Berlin"] },
  terms: [{ title: "Fees", body: "Payable within 30 days." }],
  currency: "EUR",
  generatedAtIso: "2026-08-01T10:00:00.000Z",
};

Deno.test("renders a typed-signature countersigned PDF with a real certificate", async () => {
  const bytes = await renderHireOrderPdf({
    ...BASE,
    status: "countersigned",
    signature: {
      method: "typed",
      typedName: "Ann Lee",
      signerName: "Ann Lee",
      signerEmail: "ann@x.de",
      signedAtIso: "2026-08-02T09:30:00.000Z",
      ip: "203.0.113.5",
      userAgent: "Mozilla/5.0",
      documentSha256: "a".repeat(64),
      consentText: "By signing, I agree that this is binding.",
    },
  });
  assert(bytes.length > 0, "produced PDF bytes");
  assert(bytes[0] === 0x25 && bytes[1] === 0x50, "starts with %P (PDF header)");

  // The certificate is an audit page — assert it actually SAYS the audit facts,
  // so a swapped or mislabeled field would be caught (not just that bytes exist).
  // ("Signature certificate" is deliberately NOT asserted: react-pdf drops the
  // "fi" ligature, so the heading extracts as "certicate" — a known pdfText gap.)
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Ann Lee"); // signer
  assertStringIncludes(text, "Typed signature"); // method label
  assertStringIncludes(text, "a".repeat(64)); // document SHA-256
  assertStringIncludes(text, "By signing, I agree that this is binding."); // consent
  // Signed-at now carries minute precision so two same-day signatures differ.
  assertStringIncludes(text, "02/08/2026 09:30");
});

Deno.test("renders a drawn-signature countersigned PDF with a real certificate", async () => {
  // 2x1 opaque RGBA PNG: #15131C background + white ink. A transparent PNG with
  // white ink can render invisibly on the white PDF page, so keep this fixture
  // representative of the contrast-bearing dark-mode export.
  const png =
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAADklEQVR4nGMQFZb5DwIAEM8FQMsechsAAAAASUVORK5CYII=";
  assertEquals(
    await decodeSignatureFixturePixels(png),
    new Uint8Array([0x15, 0x13, 0x1c, 0xff, 0xff, 0xff, 0xff, 0xff]),
    "signature bitmap has an opaque non-white background pixel and opaque white ink",
  );
  const bytes = await renderHireOrderPdf({
    ...BASE,
    status: "countersigned",
    signature: {
      method: "drawn",
      imageDataUrl: png,
      signerName: "Ann Lee",
      signedAtIso: "2026-08-02T09:30:00.000Z",
      documentSha256: "b".repeat(64),
      consentText: "By signing, I agree that this is binding.",
    },
  });
  assert(bytes.length > 0 && bytes[0] === 0x25, "produced a PDF");
  assertStringIncludes(
    new TextDecoder("latin1").decode(bytes),
    "/Subtype /Image",
    "drawn signature is embedded as an image XObject",
  );

  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Ann Lee"); // signer
  assertStringIncludes(text, "Drawn signature"); // method label
  assertStringIncludes(text, "b".repeat(64)); // document SHA-256
  assertStringIncludes(text, "By signing, I agree that this is binding."); // consent
  assertStringIncludes(text, "02/08/2026 09:30"); // minute-precision signed-at
});

Deno.test("issued render (no signature) is unchanged shape", async () => {
  const bytes = await renderHireOrderPdf(BASE);
  assert(bytes.length > 0 && bytes[0] === 0x25);
});

Deno.test("issued render embeds the org agent signature image on the producer line when present", async () => {
  const png =
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAADklEQVR4nGMQFZb5DwIAEM8FQMsechsAAAAASUVORK5CYII=";
  const bytes = await renderHireOrderPdf({
    ...BASE,
    letterhead: { ...BASE.letterhead, agent_signature_data_url: png },
  });
  assert(bytes.length > 0 && bytes[0] === 0x25, "produced a PDF");
  assertStringIncludes(
    new TextDecoder("latin1").decode(bytes),
    "/Subtype /Image",
    "agent signature is embedded as an image XObject on the producer line",
  );
});

Deno.test("aggregate PDF renders every engagement date with its own running order beneath it", async () => {
  // Task B3: once B1/B2 populate each engagement date's own `sessions`, an
  // aggregate order (2+ dates) must render each date's Call/Time rows beneath
  // that date's own date/venue/city line, in document order.
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      engagement_dates: {
        value: [
          {
            show_date_id: "sd-1",
            date: "2026-08-15",
            venue: "Tempodrom",
            city: "Berlin",
            sessions: ["18:00", "20:00"],
          },
          {
            show_date_id: "sd-2",
            date: "2026-08-16",
            venue: "Kulturhaus",
            city: "Hamburg",
            sessions: ["19:30"],
          },
        ],
        source: "showflow",
      },
    },
  });

  assert(bytes.length > 0 && bytes[0] === 0x25, "produced a PDF");
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Engagement dates");
  assertStringIncludes(text, "15/08/2026");
  assertStringIncludes(text, "Tempodrom");
  assertStringIncludes(text, "Berlin");
  assertStringIncludes(text, "16/08/2026");
  assertStringIncludes(text, "Kulturhaus");
  assertStringIncludes(text, "Hamburg");
  // Each date's own session times render, in document order beneath its row.
  assertStringIncludes(text, "18:00");
  assertStringIncludes(text, "20:00");
  assertStringIncludes(text, "19:30");
  // The facts strip's summary joins both dates ("15/08/2026 · 16/08/2026"),
  // so a bare "16/08/2026" also occurs before the "Engagement dates" section;
  // anchor on the date+venue run, which only occurs once (in its own row).
  assertStringIncludes(text, "16/08/2026Kulturhaus");
  assert(
    text.indexOf("Engagement dates") < text.indexOf("18:00"),
    "the engagement dates heading renders before any per-date session time",
  );
  assert(
    text.indexOf("18:00") < text.indexOf("16/08/2026Kulturhaus"),
    "the first date's own sessions render before the second date's row",
  );
  assert(
    text.indexOf("16/08/2026Kulturhaus") < text.indexOf("19:30"),
    "the second date's own session renders beneath its own row",
  );
});

Deno.test("aggregate PDF with two dates renders both dates' distinct session times and suppresses the shared table", async () => {
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      // The fixture's own top-level `sessions` is ["19:00", "21:00"]; the two
      // engagement dates below use disjoint times so a leaked shared table
      // would be distinguishable from genuine per-date rendering.
      engagement_dates: {
        value: [
          {
            show_date_id: "sd-1",
            date: "2026-09-01",
            venue: "Astra",
            city: "Berlin",
            sessions: ["17:15", "19:15"],
          },
          {
            show_date_id: "sd-2",
            date: "2026-09-02",
            venue: "Docks",
            city: "Hamburg",
            sessions: ["18:45"],
          },
        ],
        source: "showflow",
      },
    },
  });

  const text = await extractPdfText(bytes);
  // Both dates' own distinct session times render.
  assertStringIncludes(text, "17:15");
  assertStringIncludes(text, "19:15");
  assertStringIncludes(text, "18:45");
  // The shared top-level running order (this fixture's own `sessions` field,
  // 19:00/21:00) is suppressed entirely once the order is an aggregate: no
  // "Running order" heading, and neither of its own times leak into the text.
  assertEquals(text.includes("Running order"), false);
  assertEquals(text.includes("19:00"), false);
  assertEquals(text.includes("21:00"), false);
});

Deno.test("single engagement date still renders the one shared top-level running order unchanged", async () => {
  // 0 or 1 engagement dates is NOT an aggregate: the per-date rendering path
  // must not engage, and the single shared running-order table (sourced from
  // the order's own top-level `sessions`) renders exactly as it does with no
  // engagement_dates at all.
  const text = await extractPdfText(await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-06-15", venue: "Colosseum Berlin", city: "Berlin" },
        ],
        source: "showflow",
      },
    },
  }));

  assertEquals(text.includes("Engagement dates"), false);
  assertStringIncludes(text, "Running order, Colosseum Berlin");
  assertStringIncludes(text, "Session 1");
  assertStringIncludes(text, "19:00");
  assertStringIncludes(text, "Session 2");
  assertStringIncludes(text, "21:00");
});

Deno.test("single-date PDF retains the legacy date presentation", async () => {
  const text = await extractPdfText(await renderHireOrderPdf({
    ...BASE,
    data: {
      ...BASE.data,
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-08-15", venue: "Tempodrom", city: "Berlin" },
        ],
        source: "showflow",
      },
    },
  }));

  assertEquals(text.includes("Engagement dates"), false);
  assertStringIncludes(text, "15/08/2026");
  assertStringIncludes(text, "Tempodrom");
});

Deno.test("aggregate PDF still renders order-level notes (not dropped just because it has 2+ dates)", async () => {
  // notes is editable for aggregates (HireOrderEditPage notes field) and is the
  // document of record -- an aggregate order must not silently omit it just
  // because the single-date running-order block (which used to be the only
  // place notes rendered) is gated off for isAggregate.
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      notes: { value: "Load-in via the stage door from 17:00.", source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-08-15", venue: "Tempodrom", city: "Berlin", sessions: ["18:00"] },
          { show_date_id: "sd-2", date: "2026-08-16", venue: "Kulturhaus", city: "Hamburg", sessions: ["19:30"] },
        ],
        source: "showflow",
      },
    },
  });

  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Engagement dates");
  assertStringIncludes(text, "Notes: Load-in via the stage door from 17:00.");
});

Deno.test("single-date PDF still renders its order-level notes unchanged", async () => {
  // Guards against the aggregate fix double-rendering or dropping notes for the
  // 0/1-engagement-date (non-aggregate) shape.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertStringIncludes(text, "Notes: Backline provided by the venue.");
  // Exactly one occurrence -- the fix must not duplicate the notes line.
  const occurrences = text.split("Notes: Backline provided by the venue.").length - 1;
  assertEquals(occurrences, 1, "notes must render exactly once for a single-date order");
});

/** Same text-extraction pattern used throughout this file, as a named helper
 *  for the fee-breakdown tests below. */
async function renderToText(input: RenderInput): Promise<string> {
  return await extractPdfText(await renderHireOrderPdf(input));
}

Deno.test("fees section prints a per-date breakdown for an aggregate order", async () => {
  const text = await renderToText({
    ...BASE,
    data: {
      ...BASE.data,
      fee: { value: 1500, source: "manual" },
      fee_basis: { value: "per_date", source: "manual" },
      fee_per_date: { value: 500, source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "d1", date: "2026-06-15", venue: "A", city: "Berlin" },
          { show_date_id: "d2", date: "2026-06-16", venue: "B", city: "Hamburg" },
          { show_date_id: "d3", date: "2026-06-17", venue: "C", city: "Munich" },
        ],
        source: "showflow",
      },
    },
  });
  assertStringIncludes(text, "500.00 per date x 3 dates");
  assertStringIncludes(text, "1,500.00");
});

Deno.test("fees section keeps the plain engagement-fee label for a total-basis order", async () => {
  const text = await renderToText({
    ...BASE,
    data: {
      ...BASE.data,
      fee: { value: 1500, source: "manual" },
      fee_basis: { value: "total", source: "manual" },
    },
  });
  assertStringIncludes(text, "Engagement fee");
  assertEquals(text.includes("per date"), false);
});

Deno.test("fees section prints the singular per-date breakdown for a single-date per-date order", async () => {
  // A single-date order carries no `engagement_dates` (per Task 4: fee_basis
  // can be "per_date" even for a 1-date order), so engagementDates.length is 0
  // and the renderer falls back to a date count of 1, using the singular
  // template rather than "x 1 dates".
  const text = await renderToText({
    ...BASE,
    data: {
      ...BASE.data,
      fee: { value: 500, source: "manual" },
      fee_basis: { value: "per_date", source: "manual" },
      fee_per_date: { value: 500, source: "manual" },
    },
  });
  assertStringIncludes(text, "500.00 per date");
  assertEquals(text.includes("dates"), false);
});

Deno.test("fees section refuses a breakdown that does not multiply up to the stored total", async () => {
  // A snapshot whose derived fields contradict its own total: 500 per date x 3
  // dates is 1500, but the stored fee is 1200 (what a later fee edit that kept
  // the derived fields leaves behind). Printing "500.00 per date x 3 dates"
  // above a 1,200.00 total would put false arithmetic on an immutable,
  // artist-facing document, so the renderer degrades to the plain label. This
  // guard covers ANY writer, present or future, not just the one that was
  // fixed alongside it.
  const text = await renderToText({
    ...BASE,
    data: {
      ...BASE.data,
      fee: { value: 1200, source: "manual" },
      fee_basis: { value: "per_date", source: "manual" },
      fee_per_date: { value: 500, source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "d1", date: "2026-06-15", venue: "A", city: "Berlin" },
          { show_date_id: "d2", date: "2026-06-16", venue: "B", city: "Hamburg" },
          { show_date_id: "d3", date: "2026-06-17", venue: "C", city: "Munich" },
        ],
        source: "showflow",
      },
    },
  });
  assertStringIncludes(text, "Engagement fee");
  assertStringIncludes(text, "1,200.00");
  assertEquals(text.includes("per date"), false);
  assertEquals(text.includes("500.00"), false);
});

Deno.test("fees section prints a fractional per-date breakdown that reconciles only in cents", async () => {
  // 500.10 x 3 is 1500.3000000000002 in binary floating point: a float equality
  // check in the guard would reject this CORRECT breakdown and silently drop
  // the line. The reconcile runs in integer cents, so it prints.
  const text = await renderToText({
    ...BASE,
    data: {
      ...BASE.data,
      fee: { value: 1500.3, source: "manual" },
      fee_basis: { value: "per_date", source: "manual" },
      fee_per_date: { value: 500.1, source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "d1", date: "2026-06-15", venue: "A", city: "Berlin" },
          { show_date_id: "d2", date: "2026-06-16", venue: "B", city: "Hamburg" },
          { show_date_id: "d3", date: "2026-06-17", venue: "C", city: "Munich" },
        ],
        source: "showflow",
      },
    },
  });
  assertStringIncludes(text, "500.10 per date x 3 dates");
  assertStringIncludes(text, "1,500.30");
});

Deno.test("fees section renders the plain engagement-fee label unchanged for a legacy order with no fee_basis snapshot", async () => {
  // Every hire order created before this feature has no fee_basis/fee_per_date
  // in its snapshot, and issued orders are immutable, so this shape renders
  // forever going forward. It must keep printing exactly what it prints today:
  // the plain "Engagement fee" label and the unchanged total.
  const text = await renderToText(BASE);
  assertStringIncludes(text, "Engagement fee");
  assertStringIncludes(text, "850.00");
  assertEquals(text.includes("per date"), false);
});

/**
 * pdfkit/fontkit stamp three things into every render from wall-clock time or
 * randomness, never from anything this renderer controls: a random 6-letter
 * subset tag per embedded font subset (e.g. "NCGJHG+Geist-SemiBold", a fresh
 * tag on every call), the `/CreationDate` (a real `new Date()`, NOT
 * `generatedAtIso` — that only feeds the printed footer text), and the
 * trailer `/ID` (a hash seeded by those). Confirmed empirically: rendering
 * the exact same `RenderInput` twice, 5 times over, differs in exactly these
 * bytes every time and nowhere else. A raw `assertEquals` on the two
 * `Uint8Array`s would therefore fail on every run regardless of whether
 * `buildStyles` is correct, which is a worse instrument than the length
 * check it would replace. Blanking exactly these three patterns first is
 * what makes a true content-equality check on everything the theme DOES
 * control (every font size, colour, weight, letter-spacing, margin) both
 * meaningful and stable.
 */
function normalizeVolatilePdfBytes(bytes: Uint8Array): string {
  return new TextDecoder("latin1").decode(bytes)
    .replace(/[A-Z]{6}\+/g, "SUBSET+")
    .replace(/\(D:\d{14}Z\)/g, "(D:NORMALIZED)")
    .replace(/<[0-9a-f]{32}>/g, "<NORMALIZED>");
}

// ── golden fixtures: the built-in defaults must keep rendering as they do ──
//
// WHY A GOLDEN AND NOT A SELF-COMPARISON: the test below this block pins
// `resolveHireOrderTheme() === HIRE_ORDER_THEME_DEFAULTS`, which is a real
// property but a narrow one - both of its operands are computed from the same
// defaults, so a one-character change to a default size or colour moves both
// sides together and the assertion still passes. The acceptance gate for the
// whole theming refactor was "the defaults render byte-for-byte what they
// rendered BEFORE the refactor". Nothing in-process can express that, because
// the pre-refactor renderer no longer exists. A committed fixture can: these
// two hashes were computed from the post-refactor renderer at the point where
// byte-identity to pre-refactor output had been verified against a temporary
// worktree of the pre-refactor commit, so pinning them forward pins that
// property forward. From here, ANY change to a built-in default or to the
// renderer's structure fails these two tests and has to be looked at.
//
// DETERMINISM: normalizeVolatilePdfBytes blanks the only three things pdfkit
// stamps from wall-clock time or randomness (see its own doc comment). What is
// left is reproducible across processes and machines given the pinned
// @react-pdf/renderer (deno.lock: 4.5.1) and the pinned Deno (CI: v2.5.6).
// A version bump of either is expected to fail these, which is the point: it
// is a renderer change to every org's legal document and should be reviewed,
// not absorbed silently.
//
// HASH, NOT BYTES: this used to compare against two committed *.golden files
// (~118KB combined) holding the full normalized output. Those files lived
// under supabase/functions/_shared/hire-order-pdf/, and the Supabase preview
// deploy started failing with a 413 (request entity too large) once they were
// added, on top of fonts.ts (~708KB of embedded base64 font data, already
// close to whatever the ceiling is). A SHA-256 of the same normalized string
// gives identical guard strength - any byte change still fails - at 64 hex
// characters instead of tens of kilobytes. Kept as an inline constant here
// rather than a third small file, since a file of any size in this directory
// is a candidate for being swept into a future deploy payload; a value baked
// into the test source is not a file that can be added to that tree at all.
//
// REGENERATING (only when the change is intended, and review the diff):
//   UPDATE_HIRE_ORDER_PDF_GOLDEN=1 \
//     deno test --allow-all --node-modules-dir=none supabase/functions/
// This does not fail the test; it logs the new hash to paste into
// GOLDEN_HASHES below, plus a temp-file path holding the full normalized
// output so the change can be reviewed before committing the new hash.

/** Expected SHA-256 (hex) of the normalized render for each golden fixture.
 *  Regenerate via UPDATE_HIRE_ORDER_PDF_GOLDEN=1 (see above) - it logs the
 *  new hash rather than writing it here, since only a human reviewing the
 *  rendered diff should decide to move this pin. */
const GOLDEN_HASHES: Record<string, string> = {
  "countersigned-aggregate": "50270c4a71f827e59c20cb0a60a1908e5f4f31c1c37b8577c5c3d5d30e90021d",
  "single-date-preview": "0b93274c735ce20d9a048c2b8530a606045dadb5a6b033ee23bd6cb2879b3ca3",
};

async function sha256Hex(text: string): Promise<string> {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(digest)).map((byte) => byte.toString(16).padStart(2, "0")).join("");
}

/** Dumps the full normalized render to a temp file so a mismatch (or a
 *  regeneration) can be inspected or diffed by hand, without committing the
 *  bytes anywhere. */
async function writeActualDump(name: string, actual: string): Promise<string> {
  const path = await Deno.makeTempFile({
    prefix: `hire-order-pdf-golden-${name}-`,
    suffix: ".actual.txt",
  });
  await Deno.writeTextFile(path, actual);
  return path;
}

async function assertMatchesGolden(name: string, bytes: Uint8Array): Promise<void> {
  const actual = normalizeVolatilePdfBytes(bytes);
  const actualHash = await sha256Hex(actual);

  if (Deno.env.get("UPDATE_HIRE_ORDER_PDF_GOLDEN") === "1") {
    const dumpPath = await writeActualDump(name, actual);
    console.log(
      `[golden:${name}] sha256 ${actualHash}\n` +
        `  Paste this into GOLDEN_HASHES["${name}"] in render.test.ts once you have\n` +
        `  reviewed the change. Full normalized output written to:\n` +
        `    ${dumpPath}`,
    );
    return;
  }

  const expectedHash = GOLDEN_HASHES[name];
  if (expectedHash === undefined) {
    throw new Error(
      `golden hash "${name}" is missing from GOLDEN_HASHES in render.test.ts. If this is a new fixture, generate it with:\n` +
        `  UPDATE_HIRE_ORDER_PDF_GOLDEN=1 deno test --allow-all --node-modules-dir=none supabase/functions/`,
    );
  }
  if (actualHash === expectedHash) return;

  const dumpPath = await writeActualDump(name, actual);
  throw new Error(
    `the default-theme render of "${name}" changed.\n\n` +
      `This document is what every org's hire order looks like with no theme override, so a\n` +
      `change here restyles a legal document. The usual cause is an edited built-in default in\n` +
      `pdfTheme.ts (a size, weight, colour, letter-spacing or page margin) or a structural change\n` +
      `in render.tsx.\n\n` +
      `  expected sha256: ${expectedHash}\n` +
      `  actual   sha256: ${actualHash}\n` +
      `  full normalized output (${actual.length} chars) written to:\n` +
      `    ${dumpPath}\n\n` +
      `To see exactly what changed, diff that file against a dump of the pre-change render (re-run\n` +
      `this same command against the commit before your change, with UPDATE_HIRE_ORDER_PDF_GOLDEN=1,\n` +
      `to get the other side of the diff).\n\n` +
      `If the change is intended, update GOLDEN_HASHES["${name}"] to the actual hash above:\n` +
      `  UPDATE_HIRE_ORDER_PDF_GOLDEN=1 deno test --allow-all --node-modules-dir=none supabase/functions/`,
  );
}

/** A countersigned aggregate: three engagement dates with their own running
 *  orders, order-level notes, a reconciling per-date fee breakdown, terms, a
 *  typed signature mark and therefore the signature certificate page. Between
 *  them these two fixtures reach every section the renderer can draw. */
function goldenCountersignedAggregate(): RenderInput {
  const base = makeRenderFixture();
  return {
    ...base,
    status: "countersigned",
    generatedAtIso: "2026-08-01T10:00:00.000Z",
    data: {
      ...base.data,
      fee: { value: "4500.00", source: "sheet" },
      fee_basis: { value: "per_date", source: "manual" },
      fee_per_date: { value: "1500.00", source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "g-1", date: "2026-06-15", venue: "Colosseum Berlin", city: "Berlin", sessions: ["19:00", "21:00"], duration_min: 90 },
          { show_date_id: "g-2", date: "2026-06-16", venue: "Kammerspiele", city: "Hamburg", sessions: ["19:30"], duration_min: 90 },
          { show_date_id: "g-3", date: "2026-06-17", venue: "Volksbuehne", city: "Munich", sessions: ["18:00", "20:30"], duration_min: 120 },
        ],
        source: "showflow",
      },
    },
    signature: {
      method: "typed",
      typedName: "Mara Müller",
      signerName: "Mara Müller",
      signerEmail: "mara@example.de",
      signedAtIso: "2026-06-02T09:30:00.000Z",
      ip: "203.0.113.5",
      userAgent: "Mozilla/5.0",
      documentSha256: "c".repeat(64),
      consentText: "By signing, I agree that this is binding.",
    },
  };
}

/** A single-date preview: the watermark, the one shared top-level running
 *  order, and no terms section at all. Deliberately the opposite shape to the
 *  aggregate above. */
function goldenSingleDatePreview(): RenderInput {
  return {
    ...makeRenderFixture(),
    status: "preview",
    terms: [],
    generatedAtIso: "2026-08-01T10:00:00.000Z",
  };
}

Deno.test("countersigned aggregate renders exactly as the committed golden", async () => {
  await assertMatchesGolden("countersigned-aggregate", await renderHireOrderPdf(goldenCountersignedAggregate()));
});

Deno.test("single-date preview renders exactly as the committed golden", async () => {
  await assertMatchesGolden("single-date-preview", await renderHireOrderPdf(goldenSingleDatePreview()));
});

Deno.test("default theme renders byte-identically to no theme at all", async () => {
  const withoutTheme = await renderHireOrderPdf({ ...BASE, generatedAtIso: "2026-08-01T10:00:00.000Z" });
  const withTheme = await renderHireOrderPdf({
    ...BASE,
    generatedAtIso: "2026-08-01T10:00:00.000Z",
    theme: resolveHireOrderTheme(),
  });
  // Full content equality, not a length check: two transcription errors with
  // equal net encoded length would both slip through a scalar comparison.
  // See normalizeVolatilePdfBytes for why the raw bytes aren't compared directly.
  assertEquals(normalizeVolatilePdfBytes(withTheme), normalizeVolatilePdfBytes(withoutTheme));
});

Deno.test("a theme override changes the rendered document", async () => {
  const plain = await renderHireOrderPdf({ ...BASE, generatedAtIso: "2026-08-01T10:00:00.000Z" });
  const scaled = await renderHireOrderPdf({
    ...BASE,
    generatedAtIso: "2026-08-01T10:00:00.000Z",
    theme: resolveHireOrderTheme({ base: { scale: 1.4 } }),
  });
  assertNotEquals(scaled.length, plain.length);
});

Deno.test("buildStyles applies role size, weight and colour", () => {
  const theme = resolveHireOrderTheme({
    roles: { sectionHeading: { size: 20, weight: 400, color: "accent" } },
  });
  const s = buildStyles(theme);
  assertEquals(s.sectionHeading.fontSize, 20);
  assertEquals(s.sectionHeading.fontWeight, 400);
  assertEquals(s.sectionHeading.color, theme.base.colors.accent);
  // Structure survives the theming.
  assertEquals(s.sectionHeading.marginBottom, 8);
});

Deno.test("buildStyles applies base scale and page margins", () => {
  const theme = resolveHireOrderTheme({ base: { scale: 1.5, page: { marginX: 60 } } });
  const s = buildStyles(theme);
  assertEquals(s.sectionHeading.fontSize, 18);
  assertEquals(s.page.paddingHorizontal, 60);
  assertEquals(s.footer.left, 60);
  assertEquals(s.footer.right, 60);
});

Deno.test("highlightRole changes the rendered document", async () => {
  const plain = await renderHireOrderPdf({ ...BASE, generatedAtIso: "2026-08-01T10:00:00.000Z" });
  const lit = await renderHireOrderPdf({
    ...BASE,
    generatedAtIso: "2026-08-01T10:00:00.000Z",
    highlightRole: "sectionHeading",
  });
  assertNotEquals(lit.length, plain.length);
});

Deno.test("highlightRole is ignored for a role the document does not use", async () => {
  const plain = await renderHireOrderPdf({ ...BASE, generatedAtIso: "2026-08-01T10:00:00.000Z" });
  const lit = await renderHireOrderPdf({
    ...BASE,
    generatedAtIso: "2026-08-01T10:00:00.000Z",
    // BASE has no signature, so the certificate page is absent.
    highlightRole: "certLabel",
  });
  assertEquals(lit.length, plain.length);
});

Deno.test("overriding one role's family does not change the page's inherited default font", () => {
  // Regression: the page's fontFamily used to be read back out of
  // themeRoleStyle(theme, "titleLead") rather than resolved from
  // theme.base.fontFamily directly. That was byte-identical only by
  // coincidence (no default role sets an explicit `family`) and would have
  // silently dragged the whole document onto titleLead's font the moment a
  // per-role override existed, as it does here.
  const theme = resolveHireOrderTheme({ roles: { titleLead: { family: "inter" } } });
  const s = buildStyles(theme);
  assertEquals(s.titleLead.fontFamily, "Inter");
  assertEquals(s.page.fontFamily, "Geist");
});
