import { assert, assertEquals, assertStringIncludes } from "https://deno.land/std@0.224.0/assert/mod.ts";
import type { RenderInput } from "../hireOrders.ts";
import { renderHireOrderPdf } from "./render.tsx";
import { extractPdfText } from "./pdfText.ts";

/** A full OrderData plus letterhead and terms — the shape Task 8 will pass. */
function makeRenderFixture(): RenderInput {
  return {
    data: {
      artist_name: { value: "Mara Müller", source: "showflow" },
      recipient_email: { value: "mara@example.de", source: "showflow" },
      role: { value: "Lead vocalist", source: "showflow" },
      cast: { value: "Berlin 1", source: "showflow" },
      date: { value: "2026-06-15", source: "showflow" },
      venue: { value: "Colosseum Berlin", source: "sheet" },
      city: { value: "Berlin", source: "showflow" },
      duration_min: { value: 90, source: "manual" },
      sessions: { value: ["19:00", "21:00"], source: "showflow" },
      fee: { value: "4500.00", source: "sheet" },
      currency: { value: "EUR", source: "default" },
      notes: { value: "Backline provided by the venue.", source: "manual" },
    },
    orderNo: "HO-2026-0615-B1",
    status: "issued",
    letterhead: {
      legal_name: "Nord Productions GmbH",
      address_lines: ["Chausseestrasse 12", "10115 Berlin", "Germany"],
      registration_line: "HRB 123456 B, VAT DE123456789",
      agent_name: "Jonas Wagner",
      agent_email: "jonas@nordproductions.de",
    },
    terms: [
      {
        title: "Engagement",
        body: "The Producer engages the Artist to perform at the venue on the date stated above.",
      },
      {
        title: "Cancellation",
        body: "Either party may cancel in writing no later than 14 days before the performance date.",
      },
    ],
    currency: "EUR",
    generatedAtIso: "2026-05-02T09:30:00.000Z",
  };
}

Deno.test("renders a parseable pdf with the core fields", async () => {
  const bytes = await renderHireOrderPdf(makeRenderFixture());

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  assert(bytes.length > 5_000, `expected a real document, got ${bytes.length} bytes`);

  // Assert what the document SAYS, not just that bytes exist: a PDF of the
  // right size with blank pages would pass the two checks above.
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Performance hire order");
  assertStringIncludes(text, "HO-2026-0615-B1");
  assertStringIncludes(text, "Nord Productions GmbH");
  assertStringIncludes(text, "Colosseum Berlin");
  assertStringIncludes(text, "Lead vocalist");
  assertStringIncludes(text, "Berlin 1");
  assertStringIncludes(text, "15/06/2026");
  assertStringIncludes(text, "90 min");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "Generated by ShowFlow Pro");
  // Running order rows come from `sessions`.
  assertStringIncludes(text, "Session 1");
  assertStringIncludes(text, "19:00");
  assertStringIncludes(text, "Session 2");
  assertStringIncludes(text, "21:00");
  // Terms are the caller's, rendered as numbered clauses.
  assertStringIncludes(text, "Terms & conditions");
  assertStringIncludes(text, "Engagement.");
  assertStringIncludes(text, "Either party may cancel in writing");
  // Both signature lines.
  assertStringIncludes(text, "For the Producer");
  assertStringIncludes(text, "The Artist");
});

Deno.test("embeds glyphs for non-ASCII copy rather than dropping them", async () => {
  // The Task 5 spike ran ASCII-only against a Latin-subset font and flagged
  // that unmapped glyphs would silently render as notdef. These assert the
  // full fonts really carry the umlaut and the euro sign.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));
  assertStringIncludes(text, "Mara Müller");
  assertStringIncludes(text, "€4,500.00");
});

Deno.test("preview watermark only in preview status", async () => {
  const issued = await renderHireOrderPdf({ ...makeRenderFixture(), status: "issued" });
  const preview = await renderHireOrderPdf({ ...makeRenderFixture(), status: "preview" });

  // Assert the watermark by its text, not by `preview.length !== issued.length`
  // (which any styling difference would satisfy).
  assertStringIncludes(await extractPdfText(preview), "PREVIEW");
  assertEquals((await extractPdfText(issued)).includes("PREVIEW"), false);
});

Deno.test("renders without a dangling heading when the org has no terms", async () => {
  // Org terms ship empty by product decision, so this is the default document,
  // not an edge case.
  const bytes = await renderHireOrderPdf({ ...makeRenderFixture(), terms: [] });

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  const text = await extractPdfText(bytes);
  assertEquals(text.includes("Terms & conditions"), false);
  // The rest of the document still renders.
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "For the Producer");
});

Deno.test("renders only an engagement fee, never a deposit or balance", async () => {
  // v1 is fee-only: the design mock's deposit/balance rows are a non-goal.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertStringIncludes(text, "Engagement fee");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertEquals(text.includes("Deposit"), false);
  assertEquals(text.includes("Balance"), false);
});

Deno.test("renders no em-dashes or en-dashes in the document copy", async () => {
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertEquals(text.includes("—"), false, "em-dash found in rendered copy");
  assertEquals(text.includes("–"), false, "en-dash found in rendered copy");
});
