import { assert, assertEquals, assertStringIncludes } from "https://deno.land/std@0.224.0/assert/mod.ts";
import type { RenderInput } from "../hireOrders.ts";
import { renderHireOrderPdf } from "./render.tsx";
import { extractPdfText } from "./pdfText.ts";

/** Decode the single unfiltered RGBA scanline used by the tiny signature fixture. */
async function decodeSignatureFixturePixels(dataUrl: string): Promise<Uint8Array> {
  const encoded = dataUrl.slice(dataUrl.indexOf(",") + 1);
  const png = Uint8Array.from(atob(encoded), (char) => char.charCodeAt(0));
  const idatParts: Uint8Array[] = [];
  let offset = 8; // PNG signature
  while (offset < png.length) {
    const length = new DataView(png.buffer, png.byteOffset + offset, 4).getUint32(0);
    const type = new TextDecoder().decode(png.slice(offset + 4, offset + 8));
    if (type === "IDAT") idatParts.push(png.slice(offset + 8, offset + 8 + length));
    offset += 12 + length;
  }
  const compressedBytes = new Uint8Array(
    idatParts.reduce((total, part) => total + part.length, 0),
  );
  let compressedOffset = 0;
  for (const part of idatParts) {
    compressedBytes.set(part, compressedOffset);
    compressedOffset += part.length;
  }
  const compressed = new Blob([compressedBytes.buffer]);
  const inflated = new Uint8Array(
    await new Response(
      compressed.stream().pipeThrough(new DecompressionStream("deflate")),
    ).arrayBuffer(),
  );
  assertEquals(inflated[0], 0, "fixture uses an unfiltered PNG scanline");
  return inflated.slice(1);
}

/** A full OrderData plus letterhead and terms — the shape Task 8 will pass. */
function makeRenderFixture(): RenderInput {
  return {
    data: {
      artist_name: { value: "Mara Müller", source: "showflow" },
      recipient_email: { value: "mara@example.de", source: "showflow" },
      role: { value: "Lead vocalist", source: "showflow" },
      cast: { value: "Berlin 1", source: "showflow" },
      date: { value: "2026-06-15", source: "showflow" },
      venue: { value: "Colosseum Berlin", source: "sheet" },
      city: { value: "Berlin", source: "showflow" },
      duration_min: { value: 90, source: "manual" },
      sessions: { value: ["19:00", "21:00"], source: "showflow" },
      fee: { value: "4500.00", source: "sheet" },
      currency: { value: "EUR", source: "default" },
      notes: { value: "Backline provided by the venue.", source: "manual" },
    },
    orderNo: "HO-2026-0615-B1",
    status: "issued",
    letterhead: {
      legal_name: "Nord Productions GmbH",
      address_lines: ["Chausseestrasse 12", "10115 Berlin", "Germany"],
      registration_line: "HRB 123456 B, VAT DE123456789",
      agent_name: "Jonas Wagner",
      agent_email: "jonas@nordproductions.de",
    },
    terms: [
      {
        title: "Engagement",
        body: "The Producer engages the Artist to perform at the venue on the date stated above.",
      },
      {
        title: "Cancellation",
        body: "Either party may cancel in writing no later than 14 days before the performance date.",
      },
    ],
    currency: "EUR",
    generatedAtIso: "2026-05-02T09:30:00.000Z",
  };
}

Deno.test("renders a parseable pdf with the core fields", async () => {
  const bytes = await renderHireOrderPdf(makeRenderFixture());

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  assert(bytes.length > 5_000, `expected a real document, got ${bytes.length} bytes`);

  // Assert what the document SAYS, not just that bytes exist: a PDF of the
  // right size with blank pages would pass the two checks above.
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Performance hire order");
  assertStringIncludes(text, "HO-2026-0615-B1");
  assertStringIncludes(text, "Nord Productions GmbH");
  assertStringIncludes(text, "Colosseum Berlin");
  assertStringIncludes(text, "Lead vocalist");
  assertStringIncludes(text, "Berlin 1");
  assertStringIncludes(text, "15/06/2026");
  assertStringIncludes(text, "90 min");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "Generated by ShowFlow Pro");
  // Running order rows come from `sessions`.
  assertStringIncludes(text, "Session 1");
  assertStringIncludes(text, "19:00");
  assertStringIncludes(text, "Session 2");
  assertStringIncludes(text, "21:00");
  // Terms are the caller's, rendered as numbered clauses.
  assertStringIncludes(text, "Terms & conditions");
  assertStringIncludes(text, "Engagement.");
  assertStringIncludes(text, "Either party may cancel in writing");
  // Both signature lines.
  assertStringIncludes(text, "For the Producer");
  assertStringIncludes(text, "The Artist");
});

Deno.test("embeds glyphs for non-ASCII copy rather than dropping them", async () => {
  // The Task 5 spike ran ASCII-only against a Latin-subset font and flagged
  // that unmapped glyphs would silently render as notdef. These assert the
  // full fonts really carry the umlaut and the euro sign.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));
  assertStringIncludes(text, "Mara Müller");
  assertStringIncludes(text, "€4,500.00");
});

Deno.test("preview watermark only in preview status", async () => {
  const issued = await renderHireOrderPdf({ ...makeRenderFixture(), status: "issued" });
  const preview = await renderHireOrderPdf({ ...makeRenderFixture(), status: "preview" });

  // Assert the watermark by its text, not by `preview.length !== issued.length`
  // (which any styling difference would satisfy).
  assertStringIncludes(await extractPdfText(preview), "PREVIEW");
  assertEquals((await extractPdfText(issued)).includes("PREVIEW"), false);
});

Deno.test("renders without a dangling heading when the org has no terms", async () => {
  // Org terms ship empty by product decision, so this is the default document,
  // not an edge case.
  const bytes = await renderHireOrderPdf({ ...makeRenderFixture(), terms: [] });

  assertEquals(new TextDecoder().decode(bytes.slice(0, 5)), "%PDF-");
  const text = await extractPdfText(bytes);
  assertEquals(text.includes("Terms & conditions"), false);
  // The rest of the document still renders.
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertStringIncludes(text, "For the Producer");
});

Deno.test("renders only an engagement fee, never a deposit or balance", async () => {
  // v1 is fee-only: the design mock's deposit/balance rows are a non-goal.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertStringIncludes(text, "Engagement fee");
  assertStringIncludes(text, "TOTAL PAYABLE"); // the design uppercases the total label
  assertEquals(text.includes("Deposit"), false);
  assertEquals(text.includes("Balance"), false);
});

Deno.test("renders no em-dashes or en-dashes in the document copy", async () => {
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertEquals(text.includes("—"), false, "em-dash found in rendered copy");
  assertEquals(text.includes("–"), false, "en-dash found in rendered copy");
});

const BASE: RenderInput = {
  data: {
    artist_name: { value: "Ann Lee", source: "showflow" },
    recipient_email: { value: "ann@x.de", source: "showflow" },
    date: { value: "2026-08-15", source: "showflow" },
    venue: { value: "Tempodrom", source: "showflow" },
    fee: { value: 850, source: "showflow" },
  },
  orderNo: "HO-1",
  status: "issued",
  letterhead: { legal_name: "Nord GmbH", address_lines: ["Berlin"] },
  terms: [{ title: "Fees", body: "Payable within 30 days." }],
  currency: "EUR",
  generatedAtIso: "2026-08-01T10:00:00.000Z",
};

Deno.test("renders a typed-signature countersigned PDF with a real certificate", async () => {
  const bytes = await renderHireOrderPdf({
    ...BASE,
    status: "countersigned",
    signature: {
      method: "typed",
      typedName: "Ann Lee",
      signerName: "Ann Lee",
      signerEmail: "ann@x.de",
      signedAtIso: "2026-08-02T09:30:00.000Z",
      ip: "203.0.113.5",
      userAgent: "Mozilla/5.0",
      documentSha256: "a".repeat(64),
      consentText: "By signing, I agree that this is binding.",
    },
  });
  assert(bytes.length > 0, "produced PDF bytes");
  assert(bytes[0] === 0x25 && bytes[1] === 0x50, "starts with %P (PDF header)");

  // The certificate is an audit page — assert it actually SAYS the audit facts,
  // so a swapped or mislabeled field would be caught (not just that bytes exist).
  // ("Signature certificate" is deliberately NOT asserted: react-pdf drops the
  // "fi" ligature, so the heading extracts as "certicate" — a known pdfText gap.)
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Ann Lee"); // signer
  assertStringIncludes(text, "Typed signature"); // method label
  assertStringIncludes(text, "a".repeat(64)); // document SHA-256
  assertStringIncludes(text, "By signing, I agree that this is binding."); // consent
  // Signed-at now carries minute precision so two same-day signatures differ.
  assertStringIncludes(text, "02/08/2026 09:30");
});

Deno.test("renders a drawn-signature countersigned PDF with a real certificate", async () => {
  // 2x1 opaque RGBA PNG: #15131C background + white ink. A transparent PNG with
  // white ink can render invisibly on the white PDF page, so keep this fixture
  // representative of the contrast-bearing dark-mode export.
  const png =
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAABCAYAAAD0In+KAAAADklEQVR4nGMQFZb5DwIAEM8FQMsechsAAAAASUVORK5CYII=";
  assertEquals(
    await decodeSignatureFixturePixels(png),
    new Uint8Array([0x15, 0x13, 0x1c, 0xff, 0xff, 0xff, 0xff, 0xff]),
    "signature bitmap has an opaque non-white background pixel and opaque white ink",
  );
  const bytes = await renderHireOrderPdf({
    ...BASE,
    status: "countersigned",
    signature: {
      method: "drawn",
      imageDataUrl: png,
      signerName: "Ann Lee",
      signedAtIso: "2026-08-02T09:30:00.000Z",
      documentSha256: "b".repeat(64),
      consentText: "By signing, I agree that this is binding.",
    },
  });
  assert(bytes.length > 0 && bytes[0] === 0x25, "produced a PDF");
  assertStringIncludes(
    new TextDecoder("latin1").decode(bytes),
    "/Subtype /Image",
    "drawn signature is embedded as an image XObject",
  );

  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Ann Lee"); // signer
  assertStringIncludes(text, "Drawn signature"); // method label
  assertStringIncludes(text, "b".repeat(64)); // document SHA-256
  assertStringIncludes(text, "By signing, I agree that this is binding."); // consent
  assertStringIncludes(text, "02/08/2026 09:30"); // minute-precision signed-at
});

Deno.test("issued render (no signature) is unchanged shape", async () => {
  const bytes = await renderHireOrderPdf(BASE);
  assert(bytes.length > 0 && bytes[0] === 0x25);
});

Deno.test("aggregate PDF renders every engagement date with its own running order beneath it", async () => {
  // Task B3: once B1/B2 populate each engagement date's own `sessions`, an
  // aggregate order (2+ dates) must render each date's Call/Time rows beneath
  // that date's own date/venue/city line, in document order.
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      engagement_dates: {
        value: [
          {
            show_date_id: "sd-1",
            date: "2026-08-15",
            venue: "Tempodrom",
            city: "Berlin",
            sessions: ["18:00", "20:00"],
          },
          {
            show_date_id: "sd-2",
            date: "2026-08-16",
            venue: "Kulturhaus",
            city: "Hamburg",
            sessions: ["19:30"],
          },
        ],
        source: "showflow",
      },
    },
  });

  assert(bytes.length > 0 && bytes[0] === 0x25, "produced a PDF");
  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Engagement dates");
  assertStringIncludes(text, "15/08/2026");
  assertStringIncludes(text, "Tempodrom");
  assertStringIncludes(text, "Berlin");
  assertStringIncludes(text, "16/08/2026");
  assertStringIncludes(text, "Kulturhaus");
  assertStringIncludes(text, "Hamburg");
  // Each date's own session times render, in document order beneath its row.
  assertStringIncludes(text, "18:00");
  assertStringIncludes(text, "20:00");
  assertStringIncludes(text, "19:30");
  // The facts strip's summary joins both dates ("15/08/2026 · 16/08/2026"),
  // so a bare "16/08/2026" also occurs before the "Engagement dates" section;
  // anchor on the date+venue run, which only occurs once (in its own row).
  assertStringIncludes(text, "16/08/2026Kulturhaus");
  assert(
    text.indexOf("Engagement dates") < text.indexOf("18:00"),
    "the engagement dates heading renders before any per-date session time",
  );
  assert(
    text.indexOf("18:00") < text.indexOf("16/08/2026Kulturhaus"),
    "the first date's own sessions render before the second date's row",
  );
  assert(
    text.indexOf("16/08/2026Kulturhaus") < text.indexOf("19:30"),
    "the second date's own session renders beneath its own row",
  );
});

Deno.test("aggregate PDF with two dates renders both dates' distinct session times and suppresses the shared table", async () => {
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      // The fixture's own top-level `sessions` is ["19:00", "21:00"]; the two
      // engagement dates below use disjoint times so a leaked shared table
      // would be distinguishable from genuine per-date rendering.
      engagement_dates: {
        value: [
          {
            show_date_id: "sd-1",
            date: "2026-09-01",
            venue: "Astra",
            city: "Berlin",
            sessions: ["17:15", "19:15"],
          },
          {
            show_date_id: "sd-2",
            date: "2026-09-02",
            venue: "Docks",
            city: "Hamburg",
            sessions: ["18:45"],
          },
        ],
        source: "showflow",
      },
    },
  });

  const text = await extractPdfText(bytes);
  // Both dates' own distinct session times render.
  assertStringIncludes(text, "17:15");
  assertStringIncludes(text, "19:15");
  assertStringIncludes(text, "18:45");
  // The shared top-level running order (this fixture's own `sessions` field,
  // 19:00/21:00) is suppressed entirely once the order is an aggregate: no
  // "Running order" heading, and neither of its own times leak into the text.
  assertEquals(text.includes("Running order"), false);
  assertEquals(text.includes("19:00"), false);
  assertEquals(text.includes("21:00"), false);
});

Deno.test("single engagement date still renders the one shared top-level running order unchanged", async () => {
  // 0 or 1 engagement dates is NOT an aggregate: the per-date rendering path
  // must not engage, and the single shared running-order table (sourced from
  // the order's own top-level `sessions`) renders exactly as it does with no
  // engagement_dates at all.
  const text = await extractPdfText(await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-06-15", venue: "Colosseum Berlin", city: "Berlin" },
        ],
        source: "showflow",
      },
    },
  }));

  assertEquals(text.includes("Engagement dates"), false);
  assertStringIncludes(text, "Running order, Colosseum Berlin");
  assertStringIncludes(text, "Session 1");
  assertStringIncludes(text, "19:00");
  assertStringIncludes(text, "Session 2");
  assertStringIncludes(text, "21:00");
});

Deno.test("single-date PDF retains the legacy date presentation", async () => {
  const text = await extractPdfText(await renderHireOrderPdf({
    ...BASE,
    data: {
      ...BASE.data,
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-08-15", venue: "Tempodrom", city: "Berlin" },
        ],
        source: "showflow",
      },
    },
  }));

  assertEquals(text.includes("Engagement dates"), false);
  assertStringIncludes(text, "15/08/2026");
  assertStringIncludes(text, "Tempodrom");
});

Deno.test("aggregate PDF still renders order-level notes (not dropped just because it has 2+ dates)", async () => {
  // notes is editable for aggregates (HireOrderEditPage notes field) and is the
  // document of record -- an aggregate order must not silently omit it just
  // because the single-date running-order block (which used to be the only
  // place notes rendered) is gated off for isAggregate.
  const bytes = await renderHireOrderPdf({
    ...makeRenderFixture(),
    data: {
      ...makeRenderFixture().data,
      notes: { value: "Load-in via the stage door from 17:00.", source: "manual" },
      engagement_dates: {
        value: [
          { show_date_id: "sd-1", date: "2026-08-15", venue: "Tempodrom", city: "Berlin", sessions: ["18:00"] },
          { show_date_id: "sd-2", date: "2026-08-16", venue: "Kulturhaus", city: "Hamburg", sessions: ["19:30"] },
        ],
        source: "showflow",
      },
    },
  });

  const text = await extractPdfText(bytes);
  assertStringIncludes(text, "Engagement dates");
  assertStringIncludes(text, "Notes: Load-in via the stage door from 17:00.");
});

Deno.test("single-date PDF still renders its order-level notes unchanged", async () => {
  // Guards against the aggregate fix double-rendering or dropping notes for the
  // 0/1-engagement-date (non-aggregate) shape.
  const text = await extractPdfText(await renderHireOrderPdf(makeRenderFixture()));

  assertStringIncludes(text, "Notes: Backline provided by the venue.");
  // Exactly one occurrence -- the fix must not duplicate the notes line.
  const occurrences = text.split("Notes: Backline provided by the venue.").length - 1;
  assertEquals(occurrences, 1, "notes must render exactly once for a single-date order");
});
