// The hire-order PDF. Concrete implementation of `RenderHireOrderPdf`
// (docTypes.ts's RenderInput -> Uint8Array). DUAL-HOMED: this file is
// byte-identical on both runtimes (mirror source is
// src/lib/hireOrders/pdf/render.tsx; the edge target is generated by
// `npm run sync:mirrors`, never hand-edited). It may import ONLY from
// ./pdfDeps.ts (the one deliberately-divergent per-runtime shim),
// ./docTypes.ts, ./pdfCopy.ts, ./pdfTheme.ts, and ../feeBasis.ts / ../money.ts
// (also dual-homed mirror pairs, one directory above render.tsx on both
// sides) - see renderMirror.test.ts. Both runtimes use the automatic JSX
// runtime, so no React import is needed for JSX; ReactElement comes from
// pdfDeps.ts.
//
// Layout is a translation of the design project's `HireOrderDoc` mock
// (claude.ai/design 2569fd28, hire-orders/HireOrderDoc.jsx) into react-pdf
// primitives, section order top to bottom. Deliberate deviations from the mock:
//   - v1 is FEE-ONLY: the mock's deposit and balance rows are a non-goal, so
//     there is one "Engagement fee" line and a "Total payable" row.
//   - Terms are the caller's; the mock's hardcoded clause text is not copied.
//     Orgs ship with none, so the whole section is omitted when `terms` is empty.
//   - The mock's per-row running-order "Notes" column has no data source in v1
//     (`sessions` is a list of times), so the table is Call/Time and the
//     order-level `notes` field renders beneath it.
//   - Aggregates (2+ engagement dates, Task B3) render each date's OWN
//     running order (from that date's `EngagementDate.sessions`) inline
//     beneath its date/venue/city row, instead of the single shared table;
//     the shared table only applies to 0/1 engagement dates.
//   - No em-dashes or en-dashes in rendered copy (house rule); the mock's "—"
//     and curly quotes become plain ASCII or a middot.
import { Document, Image, Page, StyleSheet, Text, View, renderToBuffer } from "./pdfDeps.ts";
import { registerFonts } from "./pdfDeps.ts";
import type { ReactElement } from "./pdfDeps.ts";
import { type EngagementDate, type OrderData, type RenderInput } from "./docTypes.ts";
import { formatMoney } from "../money.ts";
import { feeBreakdownReconciles } from "../feeBasis.ts";
import { applyTokens, HIRE_ORDER_COPY_DEFAULTS, type HireOrderCopy } from "./pdfCopy.ts";
import {
  familiesInUse,
  type FontFamilyKey,
  HIRE_ORDER_THEME_DEFAULTS,
  type HireOrderTheme,
  type RoleKey,
  safeReactPdfFamilyName,
  themeRoleStyle,
} from "./pdfTheme.ts";

// ── fonts ────────────────────────────────────────────────────────────────
// Registration itself is per-runtime (pdfDeps.ts's registerFonts): the edge
// build embeds Geist/GeistMono as base64 data URIs so the default theme never
// touches the network, while the browser build fetches every family
// (including Geist) from the public font Storage bucket. See pdfDeps.ts on
// each side for the rationale.
//
// react-pdf hyphenates at line breaks by default, which would render an org
// called "Buehnenproduktionsgesellschaft" as "Buehnenproduktions-". Names,
// venues and emails are not dictionary words; break on whole words instead.
// Both pdfDeps.ts shims register this hyphenation callback as part of
// registerFonts, so it happens exactly once per isolate/session on either
// runtime.
//
// NOTE: this only governs breaks WITHIN a text run. react-pdf also treats the
// boundary between sibling children of a <Text> as a break opportunity and
// hyphenates there regardless: `<Text>Booking agent: {name}</Text>` is two
// children and wraps to "Booking agent: Jonas Wagner-". Every interpolated
// sentence below is therefore built as ONE template literal, never split
// across JSX children. Keep it that way.

// ── styles ───────────────────────────────────────────────────────────────
// Built per render from the resolved theme. Structural properties (flex,
// borders, padding, widths, lineHeight, absolute positioning) stay here and are
// NOT editable; only typography and colour come from the theme, via
// themeRoleStyle. Adding a role means adding it to pdfTheme.ts first.

/**
 * `available` is the set `registerFonts` actually managed to load for THIS
 * render (omitted = "everything available", i.e. resolve normally — every
 * existing test call site that doesn't pass it keeps behaving exactly as
 * before). Any family key not in it renders in a react-pdf standard font
 * instead (`safeReactPdfFamilyName`), never a family name react-pdf has no
 * working registration for.
 *
 * `highlightRole` is PREVIEW-ONLY (see `RenderInput.highlightRole` in
 * docTypes.ts): every element resolving that one role gets an accent outline
 * so the settings editor can show which document element an outline row
 * selects. It must never be threaded through the issue path.
 */
export function buildStyles(
  theme: HireOrderTheme,
  available?: ReadonlySet<FontFamilyKey>,
  highlightRole?: RoleKey,
) {
  const c = theme.base.colors;
  const r = (role: RoleKey) => {
    const style = themeRoleStyle(theme, role, available);
    if (role !== highlightRole) return style;
    // Theme's own colours, not hardcoded hex, so a retheme can never make the
    // highlight invisible against its own background.
    return {
      ...style,
      backgroundColor: theme.base.colors.feeCell,
      border: `0.5pt solid ${theme.base.colors.accent}`,
    };
  };
  const { marginX, marginTop, marginBottom } = theme.base.page;
  // Resolved directly from theme.base.fontFamily, NOT via any role's
  // themeRoleStyle: the page's inherited default must stay independent of
  // whatever family a single role (e.g. titleLead) happens to resolve to,
  // so overriding one role's font never silently drags the whole document
  // along with it (see reactPdfFamilyName's doc comment in pdfTheme.ts).
  const bodyFamily = safeReactPdfFamilyName(theme.base.fontFamily, available);

  return StyleSheet.create({
    page: {
      fontFamily: bodyFamily,
      fontWeight: 400,
      fontSize: 11,
      color: c.text,
      backgroundColor: "#FFFFFF",
      paddingTop: marginTop,
      paddingBottom: marginBottom,
      paddingHorizontal: marginX,
    },

    // Letterhead
    letterhead: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
    brandRow: { flexDirection: "row", alignItems: "center", marginBottom: 6 },
    brandTile: {
      width: 26,
      height: 26,
      borderRadius: 6,
      backgroundColor: c.text,
      color: "#FFFFFF",
      fontSize: 13,
      fontWeight: 600,
      textAlign: "center",
      paddingTop: 6,
      marginRight: 8,
    },
    legalName: { ...r("legalName") },
    eyebrow: { ...r("letterheadLine"), marginTop: 2 },
    eyebrowRight: { ...r("letterheadLine"), textAlign: "right" },
    orderNo: { ...r("orderNumber"), marginTop: 3, textAlign: "right" },
    badgeRow: { flexDirection: "row", alignItems: "center", justifyContent: "flex-end", marginTop: 5 },
    badgeDot: { width: 5, height: 5, borderRadius: 2.5, marginRight: 4 },
    badgeText: { ...r("statusBadge") },

    // Title
    title: { marginTop: 22 },
    titleLead: { ...r("titleLead") },
    artistName: { ...r("artistName"), marginTop: 4 },
    titleSub: { ...r("titleSub"), marginTop: 4 },

    // Parties
    parties: { flexDirection: "row", marginTop: 22 },
    party: { flex: 1 },
    partyGap: { width: 28 },
    partyLabel: { ...r("partyLabel"), marginBottom: 5 },
    partyName: { ...r("partyName") },
    partyLine: { ...r("partyLine"), marginTop: 2 },

    // Facts strip
    facts: {
      flexDirection: "row",
      marginTop: 22,
      borderWidth: 0.5,
      borderColor: c.line,
      borderRadius: 10,
      overflow: "hidden",
    },
    factCell: { flex: 1, padding: 10 },
    factDivider: { borderLeftWidth: 0.5, borderLeftColor: c.line },
    factCellFee: { backgroundColor: c.feeCell },
    factLabel: { ...r("factLabel"), marginBottom: 3 },
    factValue: { ...r("factValue") },
    factValueMono: { ...r("factValueMono") },
    factSub: { ...r("factSub"), marginTop: 2 },

    // Section
    section: { marginTop: 20 },
    sectionHeading: { ...r("sectionHeading"), marginBottom: 8 },

    // Running order
    tableHead: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: c.line, paddingBottom: 5 },
    tableHeadCell: { ...r("tableHeadCell") },
    tableRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: c.line, paddingVertical: 6 },
    colCall: { width: "30%" },
    colTime: { width: "70%" },
    cellLabel: { ...r("tableCellLabel") },
    cellTime: { ...r("tableCellMono") },
    notes: { ...r("notes"), marginTop: 8 },

    // Aggregate engagement dates
    engagementDateRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: c.line, paddingVertical: 6 },
    engagementDateValue: { ...r("tableCellMono"), width: "28%", fontSize: 10.5 },
    engagementDatePlace: { ...r("factValue"), flex: 1, fontSize: 10.5, fontWeight: 400 },
    engagementDateCity: { ...r("partyLine"), width: "25%", fontSize: 10.5 },

    // Fees
    feeRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6 },
    feeLabel: { ...r("feeLabel") },
    feeValue: { ...r("feeValue") },
    totalRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      borderTopWidth: 1.5,
      borderTopColor: c.text,
      backgroundColor: c.surface2,
      paddingVertical: 9,
      paddingHorizontal: 10,
    },
    totalLabel: { ...r("totalLabel") },
    totalValue: { ...r("totalValue") },

    // Terms
    clause: { flexDirection: "row", marginBottom: 7 },
    clauseNo: { ...r("clauseNumber"), width: 18 },
    clauseBody: { ...r("clauseBody"), flex: 1, lineHeight: 1.4 },
    clauseTitle: { ...r("clauseTitle") },

    // Signatures
    signatures: { flexDirection: "row", marginTop: 28 },
    signature: { flex: 1 },
    signatureGap: { width: 40 },
    signatureFor: { ...r("signatureFor"), marginBottom: 26 },
    signatureLine: { borderBottomWidth: 0.5, borderBottomColor: c.text },
    signatureHint: { ...r("signatureHint"), marginTop: 5 },

    // Applied (countersigned) signature mark
    sigMarkTyped: { ...r("signatureMarkTyped"), marginBottom: 2 },
    sigMarkImage: { height: 44, marginBottom: 2, objectFit: "contain" },

    // Certificate page
    certHeading: { ...r("certHeading"), marginBottom: 4 },
    certLead: { ...r("certLead"), marginBottom: 18 },
    certRow: { flexDirection: "row", borderBottomWidth: 0.5, borderBottomColor: c.line, paddingVertical: 7 },
    certLabel: { ...r("certLabel"), width: "34%" },
    certValue: { ...r("certValue"), flex: 1 },
    certValueMono: { ...r("factValueMono"), flex: 1, fontSize: 9.5 },
    certConsent: { ...r("certLead"), marginTop: 16, marginBottom: 0, fontSize: 10, lineHeight: 1.4 },

    // Footer
    footer: {
      position: "absolute",
      bottom: 26,
      left: marginX,
      right: marginX,
      flexDirection: "row",
      justifyContent: "space-between",
      borderTopWidth: 0.5,
      borderTopColor: c.line,
      paddingTop: 8,
    },
    footerText: { ...r("footerText") },
    footerMono: { ...r("footerText"), fontFamily: r("factValueMono").fontFamily },

    // Watermark
    watermark: {
      ...r("watermark"),
      position: "absolute",
      top: 360,
      left: 90,
      opacity: 0.08,
      transform: "rotate(-30deg)",
    },
  });
}

// ── field + date helpers ─────────────────────────────────────────────────

/** Read a snapshot field as a string; "" when it was never captured. */
function str(data: OrderData, key: keyof OrderData): string {
  const value = data[key]?.value;
  if (value === undefined || value === null || value === "") return "";
  return String(value);
}

/**
 * `dd/MM/yyyy` from a `YYYY-MM-DD` string, sliced rather than parsed so no
 * timezone can shift the day (same reasoning as formatOrderNo).
 */
function formatDateDMY(dateOnly: string): string {
  if (!/^\d{4}-\d{2}-\d{2}/.test(dateOnly)) return dateOnly;
  return `${dateOnly.slice(8, 10)}/${dateOnly.slice(5, 7)}/${dateOnly.slice(0, 4)}`;
}

/** Weekday for a `YYYY-MM-DD` string, pinned to UTC so it is deterministic. */
function weekdayOf(dateOnly: string): string {
  if (!/^\d{4}-\d{2}-\d{2}/.test(dateOnly)) return "";
  const d = new Date(`${dateOnly.slice(0, 10)}T00:00:00Z`);
  if (Number.isNaN(d.getTime())) return "";
  return d.toLocaleDateString("en-GB", { weekday: "long", timeZone: "UTC" });
}

/** `dd/MM/yyyy` from a full ISO timestamp, on the UTC calendar date. */
function formatIsoDMY(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  return formatDateDMY(d.toISOString().slice(0, 10));
}

/**
 * `dd/MM/yyyy HH:MM` (UTC) from a full ISO timestamp. The signature certificate
 * is an audit record, so it needs minute precision: two signatures on the same
 * calendar day render identically with a date alone. Hour/minute are read on the
 * UTC clock (deterministic, matches the "(UTC)" label the row carries).
 */
function formatIsoDateTimeUTC(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "";
  const hh = String(d.getUTCHours()).padStart(2, "0");
  const mm = String(d.getUTCMinutes()).padStart(2, "0");
  return `${formatDateDMY(d.toISOString().slice(0, 10))} ${hh}:${mm}`;
}

/** `sessions` is a list of time strings; anything else renders no rows. */
function sessionsOf(data: OrderData): string[] {
  const value = data.sessions?.value;
  if (!Array.isArray(value)) return [];
  return value.filter((v) => v !== undefined && v !== null && v !== "").map(String);
}

/**
 * Validated engagement dates, each carrying its own `sessions`/`duration_min`
 * (Task B3). Both are optional on the stored type because legacy rows
 * predate them; normalize a missing or malformed value to `[]` / `null`
 * rather than propagating `undefined` into the renderer.
 */
function engagementDatesOf(data: OrderData): EngagementDate[] {
  const value = data.engagement_dates?.value;
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is EngagementDate => {
      if (!item || typeof item !== "object") return false;
      const row = item as Partial<EngagementDate>;
      return typeof row.show_date_id === "string" &&
        typeof row.date === "string" &&
        (row.venue === null || typeof row.venue === "string") &&
        (row.city === null || typeof row.city === "string");
    })
    .map((item) => ({
      ...item,
      sessions: Array.isArray(item.sessions) && item.sessions.every((v) => typeof v === "string")
        ? item.sessions
        : [],
      duration_min: typeof item.duration_min === "number" ? item.duration_min : null,
    }));
}

// ── document ─────────────────────────────────────────────────────────────

/** `available` is set by `renderHireOrderPdf` only — it is `registerFonts`'
 *  result for THIS render, not a caller-facing part of `RenderInput` (see
 *  `docTypes.ts`), so it is added here rather than on the shared type. */
function HireOrderDoc(input: RenderInput & { available?: ReadonlySet<FontFamilyKey> }): ReactElement {
  const { data, orderNo, status, letterhead, terms, currency, generatedAtIso, signature, available } = input;
  // Every printed string reads from here: org overrides merged over defaults by
  // the caller, or the built-in defaults when `copy` is absent (legacy callers).
  const copy: HireOrderCopy = input.copy ?? HIRE_ORDER_COPY_DEFAULTS;
  const theme = input.theme ?? HIRE_ORDER_THEME_DEFAULTS;
  const s = buildStyles(theme, available, input.highlightRole);

  const artist = str(data, "artist_name");
  const email = str(data, "recipient_email");
  const role = str(data, "role");
  const cast = str(data, "cast");
  const date = str(data, "date");
  const venue = str(data, "venue");
  const city = str(data, "city");
  const duration = str(data, "duration_min");
  const notes = str(data, "notes");
  const fee = data.fee?.value;
  const feeText = fee === undefined || fee === null || fee === ""
    ? ""
    : formatMoney(fee as string | number, currency);
  const sessions = sessionsOf(data);
  const engagementDates = engagementDatesOf(data);
  const feeBasis = str(data, "fee_basis");
  const feePerDateValue = data.fee_per_date?.value;
  // Aggregate orders carry engagement_dates; a single-date order has none, so
  // fall back to 1 rather than 0 (which would print "x 0 dates").
  const feeDateCount = engagementDates.length || 1;
  // Last mile before an immutable document: print the breakdown ONLY when it
  // reconciles with the total right above it, in integer cents. `fee_basis` /
  // `fee_per_date` are derived at draft time, and any writer that changes `fee`
  // without clearing them leaves a snapshot whose breakdown contradicts its own
  // total ("500.00 per date x 3 dates" over a 1,200.00 total). This renderer
  // formats immutable snapshots forever, for every writer that will ever exist,
  // so the guard lives here and not only in the writers.
  const feeBreakdown =
    feeBasis === "per_date" && feeBreakdownReconciles(feePerDateValue, fee, feeDateCount)
      ? applyTokens(
        feeDateCount === 1 ? copy.fees_per_date_single : copy.fees_per_date,
        {
          amount: formatMoney(feePerDateValue as string | number, currency),
          count: feeDateCount,
        },
      )
      : "";
  const isAggregate = engagementDates.length > 1;
  const dateLabel = isAggregate
    ? engagementDates.map((item) => formatDateDMY(item.date)).join(" · ")
    : formatDateDMY(date);
  const billing = role && cast
    ? applyTokens(copy.billing_role_and_cast, { role, cast })
    : cast
    ? applyTokens(copy.billing_cast_only, { cast })
    : role;

  return (
    <Document title={`Hire order ${orderNo}`} author={letterhead.legal_name} creator="ShowFlow Pro">
      <Page size="A4" style={s.page}>
        {/* Letterhead */}
        <View style={s.letterhead}>
          <View>
            <View style={s.brandRow}>
              <Text style={s.brandTile}>{(letterhead.legal_name.trim()[0] ?? "?").toUpperCase()}</Text>
              <Text style={s.legalName}>{letterhead.legal_name}</Text>
            </View>
            {letterhead.address_lines.map((line, i) => <Text key={i} style={s.eyebrow}>{line}</Text>)}
            {letterhead.registration_line ? <Text style={s.eyebrow}>{letterhead.registration_line}</Text> : null}
          </View>
          <View>
            <Text style={s.eyebrowRight}>{copy.header_eyebrow}</Text>
            <Text style={s.orderNo}>{orderNo}</Text>
            <View style={s.badgeRow}>
              <View style={[s.badgeDot, { backgroundColor: status === "preview" ? theme.base.colors.faint : theme.base.colors.accent }]} />
              <Text style={s.badgeText}>
                {status === "preview" ? copy.badge_preview : status === "countersigned" ? copy.badge_countersigned : copy.badge_issued}
              </Text>
            </View>
          </View>
        </View>

        {/* Title */}
        <View style={s.title}>
          <Text style={s.titleLead}>{copy.title_lead}</Text>
          <Text style={s.artistName}>{artist}</Text>
          {billing ? <Text style={s.titleSub}>{billing}</Text> : null}
        </View>

        {/* Parties */}
        <View style={s.parties}>
          <View style={s.party}>
            <Text style={s.partyLabel}>{copy.party_producer_label}</Text>
            <Text style={s.partyName}>{letterhead.legal_name}</Text>
            {letterhead.address_lines.map((line, i) => <Text key={i} style={s.partyLine}>{line}</Text>)}
            {letterhead.agent_name
              ? <Text style={s.partyLine}>{applyTokens(copy.party_agent, { agent_name: letterhead.agent_name })}</Text>
              : null}
            {letterhead.agent_email ? <Text style={s.partyLine}>{letterhead.agent_email}</Text> : null}
          </View>
          <View style={s.partyGap} />
          <View style={s.party}>
            <Text style={s.partyLabel}>{copy.party_artist_label}</Text>
            <Text style={s.partyName}>{artist}</Text>
            {email ? <Text style={s.partyLine}>{email}</Text> : null}
            {cast ? <Text style={s.partyLine}>{applyTokens(copy.party_cast_reference, { cast })}</Text> : null}
            {role ? <Text style={s.partyLine}>{applyTokens(copy.party_engagement, { role })}</Text> : null}
          </View>
        </View>

        {/* Facts strip */}
        <View style={s.facts}>
          <View style={s.factCell}>
            <Text style={s.factLabel}>{copy.facts_date_label}</Text>
            <Text style={s.factValueMono}>{dateLabel}</Text>
            <Text style={s.factSub}>{isAggregate ? applyTokens(copy.facts_dates_count, { count: engagementDates.length }) : weekdayOf(date)}</Text>
          </View>
          <View style={[s.factCell, s.factDivider]}>
            <Text style={s.factLabel}>{copy.facts_venue_label}</Text>
            <Text style={s.factValue}>{venue}</Text>
            <Text style={s.factSub}>{city}</Text>
          </View>
          <View style={[s.factCell, s.factDivider]}>
            <Text style={s.factLabel}>{copy.facts_performance_label}</Text>
            <Text style={s.factValueMono}>{duration ? applyTokens(copy.facts_duration, { duration }) : ""}</Text>
            <Text style={s.factSub}>{sessions.length > 1 ? applyTokens(copy.facts_sessions_count, { count: sessions.length }) : copy.facts_single_set}</Text>
          </View>
          <View style={[s.factCell, s.factDivider, s.factCellFee]}>
            <Text style={s.factLabel}>{copy.facts_fee_label}</Text>
            <Text style={s.factValueMono}>{feeText}</Text>
            <Text style={s.factSub}>{copy.facts_fee_sub}</Text>
          </View>
        </View>

        {isAggregate
          ? (
            <View style={s.section}>
              <Text style={s.sectionHeading}>{copy.engagement_dates_heading}</Text>
              {engagementDates.map((item) => (
                <View key={item.show_date_id}>
                  <View style={s.engagementDateRow} wrap={false}>
                    <Text style={s.engagementDateValue}>{formatDateDMY(item.date)}</Text>
                    <Text style={s.engagementDatePlace}>{item.venue ?? ""}</Text>
                    <Text style={s.engagementDateCity}>{item.city ?? ""}</Text>
                  </View>
                  {(item.sessions ?? []).map((time, i) => (
                    <View key={i} style={s.tableRow} wrap={false}>
                      <Text style={[s.cellLabel, s.colCall]}>{applyTokens(copy.session_label, { n: i + 1 })}</Text>
                      <Text style={[s.cellTime, s.colTime]}>{time}</Text>
                    </View>
                  ))}
                </View>
              ))}
            </View>
          )
          : null}

        {/* Running order: the single shared table only applies to 0/1
            engagement dates. Aggregates (isAggregate, 2+ dates) render each
            date's own running order inline above instead, from that date's
            own `sessions` (see the engagement-dates block). */}
        {!isAggregate && sessions.length > 0
          ? (
            <View style={s.section}>
              <Text style={s.sectionHeading}>{venue ? applyTokens(copy.running_order_heading_venue, { venue }) : copy.running_order_heading}</Text>
              <View style={s.tableHead}>
                <Text style={[s.tableHeadCell, s.colCall]}>{copy.table_call}</Text>
                <Text style={[s.tableHeadCell, s.colTime]}>{copy.table_time}</Text>
              </View>
              {sessions.map((time, i) => (
                <View key={i} style={s.tableRow} wrap={false}>
                  <Text style={[s.cellLabel, s.colCall]}>{applyTokens(copy.session_label, { n: i + 1 })}</Text>
                  <Text style={[s.cellTime, s.colTime]}>{time}</Text>
                </View>
              ))}
            </View>
          )
          : null}

        {/* Order-level notes: NOT gated on !isAggregate. It used to render only
            inside the single-date running-order block above, so a 2+-date
            (aggregate) order silently dropped its notes from the document of
            record even though notes is editable for aggregates too
            (HireOrderEditPage). Rendered as its own section so both shapes
            show it exactly once. */}
        {notes
          ? (
            <View style={s.section}>
              <Text style={s.notes}>{applyTokens(copy.notes_prefix, { notes })}</Text>
            </View>
          )
          : null}

        {/* Fees */}
        <View style={s.section}>
          <Text style={s.sectionHeading}>{copy.fees_heading}</Text>
          <View style={s.feeRow}>
            <Text style={s.feeLabel}>{feeBreakdown || copy.fees_engagement_fee}</Text>
            <Text style={s.feeValue}>{feeText}</Text>
          </View>
          <View style={s.totalRow}>
            <Text style={s.totalLabel}>{copy.fees_total}</Text>
            <Text style={s.totalValue}>{feeText}</Text>
          </View>
        </View>

        {/* Terms — omitted entirely when the org has none, so no empty heading */}
        {terms.length > 0
          ? (
            <View style={s.section}>
              <Text style={s.sectionHeading}>{copy.terms_heading}</Text>
              {terms.map((clause, i) => (
                <View key={i} style={s.clause} wrap={false}>
                  <Text style={s.clauseNo}>{i + 1}</Text>
                  <Text style={s.clauseBody}>
                    <Text style={s.clauseTitle}>{clause.title}.</Text> {clause.body}
                  </Text>
                </View>
              ))}
            </View>
          )
          : null}

        {/* Signatures */}
        <View style={s.signatures} wrap={false}>
          <View style={s.signature}>
            <Text style={s.signatureFor}>{applyTokens(copy.signature_for_producer, { legal_name: letterhead.legal_name })}</Text>
            {letterhead.agent_signature_data_url
              ? <Image style={s.sigMarkImage} src={letterhead.agent_signature_data_url} />
              : null}
            <View style={s.signatureLine} />
            <Text style={s.signatureHint}>{applyTokens(copy.signature_producer_hint, { date: formatDateDMY(date) })}</Text>
          </View>
          <View style={s.signatureGap} />
          <View style={s.signature}>
            <Text style={s.signatureFor}>{applyTokens(copy.signature_for_artist, { artist })}</Text>
            {signature
              ? (signature.method === "drawn" && signature.imageDataUrl
                ? <Image style={s.sigMarkImage} src={signature.imageDataUrl} />
                : <Text style={s.sigMarkTyped}>{signature.typedName ?? signature.signerName}</Text>)
              : null}
            <View style={s.signatureLine} />
            <Text style={s.signatureHint}>
              {signature ? applyTokens(copy.signature_signed_electronically, { date: formatIsoDMY(signature.signedAtIso) }) : copy.signature_artist_hint}
            </Text>
          </View>
        </View>

        {status === "preview" ? <Text style={s.watermark} fixed>{copy.watermark}</Text> : null}

        {/* Footer. Page numbers are rendered, not hardcoded "1 / 1": long terms
            can push the document past one page. */}
        <View style={s.footer} fixed>
          <Text style={s.footerMono}>{orderNo}</Text>
          <Text style={s.footerText}>{applyTokens(copy.footer_generated, { date: formatIsoDMY(generatedAtIso) })}</Text>
          <Text
            style={s.footerMono}
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
      {signature ? (
        <Page size="A4" style={s.page}>
          <Text style={s.certHeading}>{copy.cert_heading}</Text>
          <Text style={s.certLead}>{applyTokens(copy.cert_lead, { orderNo })}</Text>
          <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_signer}</Text><Text style={s.certValue}>{signature.signerName}</Text></View>
          {signature.signerEmail ? <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_email}</Text><Text style={s.certValue}>{signature.signerEmail}</Text></View> : null}
          <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_method}</Text><Text style={s.certValue}>{signature.method === "drawn" ? copy.cert_method_drawn : copy.cert_method_typed}</Text></View>
          <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_signed_at}</Text><Text style={s.certValue}>{applyTokens(copy.cert_signed_at_value, { datetime: formatIsoDateTimeUTC(signature.signedAtIso) })}</Text></View>
          {signature.ip ? <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_ip}</Text><Text style={s.certValue}>{signature.ip}</Text></View> : null}
          {signature.userAgent ? <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_device}</Text><Text style={s.certValue}>{signature.userAgent}</Text></View> : null}
          <View style={s.certRow}><Text style={s.certLabel}>{copy.cert_sha}</Text><Text style={s.certValueMono}>{signature.documentSha256}</Text></View>
          <Text style={s.certConsent}>{signature.consentText}</Text>
          <View style={s.footer} fixed>
            <Text style={s.footerMono}>{orderNo}</Text>
            <Text style={s.footerText}>{applyTokens(copy.footer_generated, { date: formatIsoDMY(generatedAtIso) })}</Text>
            <Text style={s.footerMono} render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`} />
          </View>
        </Page>
      ) : null}
    </Document>
  );
}

/** Concrete `RenderHireOrderPdf`. Registers the theme's fonts before
 *  rendering, so a cold isolate/session never renders with a missing family;
 *  `available` (which families genuinely loaded) flows into `HireOrderDoc` so
 *  a family `registerFonts` could not load renders in a standard font for
 *  THIS document rather than throwing — see pdfDeps.ts and pdfTheme.ts's
 *  `safeReactPdfFamilyName`. */
export async function renderHireOrderPdf(input: RenderInput): Promise<Uint8Array> {
  const theme = input.theme ?? HIRE_ORDER_THEME_DEFAULTS;
  const available = await registerFonts(familiesInUse(theme));
  return new Uint8Array(await renderToBuffer(<HireOrderDoc {...input} available={available} />));
}
