#!/usr/bin/env bash
#
# Boot the local Supabase stack and wire this checkout at it.
#
# Idempotent: safe to re-run. `supabase start` is a no-op if the stack is already
# up; on first boot it applies every migration in supabase/migrations/ and then
# supabase/seed.sql, so the three seeded logins (admin@example.com /
# producer@example.com / artist@example.com, password: showflow-dev) are usable
# immediately.
#
# What it writes: `.env.development.local` (gitignored) with the live local keys,
# INCLUDING the service-role key that e2e needs. The committed `.env.development`
# already points Vite at the local stack; this file just supplies the live keys
# and overrides the anon key in case the published constant ever drifts.
#
# Prerequisite: a running container runtime (OrbStack recommended). See
# docs/runbooks/local-development-stack.md.
#
# Usage:  npm run local:up   (or: bash scripts/local-up.sh)
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

# ── 1. Container runtime guard ───────────────────────────────────────────────
if ! docker info >/dev/null 2>&1; then
  cat >&2 <<'EOF'
✗ No container runtime is reachable (docker info failed).

  Start OrbStack (or Docker Desktop / Colima), wait for it to be ready, then
  re-run:  npm run local:up

  Don't have one? OrbStack is the lightweight recommendation on macOS:
    https://orbstack.dev  (or: brew install orbstack)
EOF
  exit 1
fi

# ── 2. Boot the stack (applies migrations + seed on first boot) ──────────────
echo "▶ Starting local Supabase stack (this can take a minute on first boot)…"
supabase start

# ── 3. Read the live local keys ──────────────────────────────────────────────
# `supabase status -o env` prints quoted KEY=VALUE pairs. On the pinned CLI the
# keys are API_URL / ANON_KEY / SERVICE_ROLE_KEY.
eval "$(supabase status -o env)"
: "${API_URL:?supabase status did not return API_URL}"
: "${ANON_KEY:?supabase status did not return ANON_KEY}"
: "${SERVICE_ROLE_KEY:?supabase status did not return SERVICE_ROLE_KEY}"

# ── 4. Write the gitignored local env ────────────────────────────────────────
env_file="$repo_root/.env.development.local"
cat > "$env_file" <<EOF
# GENERATED by scripts/local-up.sh — do not commit (gitignored via .env.*).
# Live keys for the local Supabase stack. Loaded by Vite (dev mode, highest
# priority) and by e2e/playwright.config.ts. Re-run \`npm run local:up\` to refresh.

# Frontend (Vite) — overrides the committed .env.development with live values.
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
VITE_SUPABASE_PROJECT_ID=local

# e2e setup/teardown (e2e/global-setup.ts) — service role, never committed.
SUPABASE_URL=$API_URL
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
EOF

echo
echo "✓ Local stack is up and wired."
echo "  • App:      npm run dev        → http://localhost:8080  (targets LOCAL)"
echo "  • Prod:     npm run dev:prod   → opt back into production"
echo "  • Logins:   admin@example.com / producer@example.com / artist@example.com"
echo "              password: showflow-dev"
echo "  • Verify:   npm run verify:fast   |   npm run verify:full"
echo "  • Reset:    npm run local:reset    (re-apply migrations + reseed)"
echo "  • Stop:     npm run local:down"
