// Editable hire-order PDF copy. Every static string the renderer prints is a
// key here; interpolated strings use {{token}} placeholders resolved by
// applyTokens. Per-org overrides live in the `hire_order_copy` app-setting and
// are merged over these defaults by resolveHireOrderCopy.
//
// DUAL-HOME: byte-identical to supabase/functions/_shared/hire-order-pdf/pdfCopy.ts
// (the edge renderer can't import from src/). Edit both in the same commit;
// pdfCopyMirror.test.ts enforces byte-equality. No relative imports here so the
// two files can be identical.
//
// HOUSE RULE: no em/en dashes in defaults. Use middot, comma, or period.

export type CopyKey =
  // Header + status badge
  | "header_eyebrow"
  | "badge_preview"
  | "badge_countersigned"
  | "badge_issued"
  // Title
  | "title_lead"
  | "billing_role_and_cast"
  | "billing_cast_only"
  // Parties
  | "party_producer_label"
  | "party_agent"
  | "party_artist_label"
  | "party_cast_reference"
  | "party_engagement"
  // Facts strip
  | "facts_date_label"
  | "facts_dates_count"
  | "facts_venue_label"
  | "facts_performance_label"
  | "facts_duration"
  | "facts_sessions_count"
  | "facts_single_set"
  | "facts_fee_label"
  | "facts_fee_sub"
  // Engagement dates + running order
  | "engagement_dates_heading"
  | "session_label"
  | "running_order_heading_venue"
  | "running_order_heading"
  | "table_call"
  | "table_time"
  // Notes
  | "notes_prefix"
  // Fees
  | "fees_heading"
  | "fees_engagement_fee"
  | "fees_total"
  // Terms
  | "terms_heading"
  // Signatures
  | "signature_for_producer"
  | "signature_producer_hint"
  | "signature_for_artist"
  | "signature_signed_electronically"
  | "signature_artist_hint"
  // Watermark
  | "watermark"
  // Footer
  | "footer_generated"
  // Certificate page
  | "cert_heading"
  | "cert_lead"
  | "cert_signer"
  | "cert_email"
  | "cert_method"
  | "cert_method_drawn"
  | "cert_method_typed"
  | "cert_signed_at"
  | "cert_signed_at_value"
  | "cert_ip"
  | "cert_device"
  | "cert_sha";

export type HireOrderCopy = Record<CopyKey, string>;

export const HIRE_ORDER_COPY_DEFAULTS: HireOrderCopy = {
  header_eyebrow: "Performance hire order",
  badge_preview: "Preview",
  badge_countersigned: "Countersigned",
  badge_issued: "Issued",

  title_lead: "This order confirms the engagement of",
  billing_role_and_cast: "{{role}} · billed as {{cast}}",
  billing_cast_only: "Billed as {{cast}}",

  party_producer_label: "Hiring party, the Producer",
  party_agent: "Booking agent: {{agent_name}}",
  party_artist_label: "Engaged artist, the Artist",
  party_cast_reference: "Cast reference: {{cast}}",
  party_engagement: "Engagement: {{role}}",

  facts_date_label: "Date",
  facts_dates_count: "{{count}} dates",
  facts_venue_label: "Venue",
  facts_performance_label: "Performance",
  facts_duration: "{{duration}} min",
  facts_sessions_count: "{{count}} sessions",
  facts_single_set: "Single set",
  facts_fee_label: "Engagement fee",
  facts_fee_sub: "net of VAT",

  engagement_dates_heading: "Engagement dates",
  session_label: "Session {{n}}",
  running_order_heading_venue: "Running order, {{venue}}",
  running_order_heading: "Running order",
  table_call: "Call",
  table_time: "Time",

  notes_prefix: "Notes: {{notes}}",

  fees_heading: "Fees & payment schedule",
  fees_engagement_fee: "Engagement fee",
  fees_total: "Total payable",

  terms_heading: "Terms & conditions",

  signature_for_producer: "For the Producer · {{legal_name}}",
  signature_producer_hint: "Name · Date {{date}}",
  signature_for_artist: "The Artist · {{artist}}",
  signature_signed_electronically: "Signed electronically · {{date}}",
  signature_artist_hint: "Signature · Date",

  watermark: "PREVIEW",

  footer_generated: "Generated by ShowFlow Pro · {{date}}",

  cert_heading: "Signature certificate",
  cert_lead: "Electronic signature record for hire order {{orderNo}}.",
  cert_signer: "Signer",
  cert_email: "Email",
  cert_method: "Method",
  cert_method_drawn: "Drawn signature",
  cert_method_typed: "Typed signature",
  cert_signed_at: "Signed at",
  cert_signed_at_value: "{{datetime}} (UTC)",
  cert_ip: "IP address",
  cert_device: "Device",
  cert_sha: "Document SHA-256",
};

/** Replace each {{token}} whose name is a key of `values`. Unknown {{...}} are
 *  left verbatim (a typo stays visible instead of blanking or injecting). */
export function applyTokens(
  template: string,
  values: Record<string, string | number>,
): string {
  return template.replace(/\{\{(\w+)\}\}/g, (whole, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : whole,
  );
}

/** Merge per-org overrides over the defaults. A blank/whitespace override falls
 *  back to the default; the result is always a complete record. */
export function resolveHireOrderCopy(
  overrides?: Partial<HireOrderCopy> | null,
): HireOrderCopy {
  if (!overrides) return { ...HIRE_ORDER_COPY_DEFAULTS };
  const out = { ...HIRE_ORDER_COPY_DEFAULTS };
  for (const key of Object.keys(HIRE_ORDER_COPY_DEFAULTS) as CopyKey[]) {
    const v = overrides[key];
    if (typeof v === "string" && v.trim() !== "") out[key] = v;
  }
  return out;
}
